# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3d67ab288c2594af2e6cd19565754d44f6fd0f41db5cb07af8e3f504606c8bdb3659be2c9165dacc70a4a517336067f72af378b6b2cf299fd191254502dc9893

test:
  secret_key_base: 7b083b5349a9c055150beaf1cef2b37d60d6dc9084132e7af399c67e4195603ac3ec90928f2e8527d12ec2795fd41b45a525b249cff5df446b8f97774c88b4ee

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
